version: "3.8"

services:
  producer:
    build: .
    command: node producer.js
    ports:
      - "3001:3001"
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      QUEUE_NAME: email_queue
      PORT: 3001

  consumer:
    build: .
    command: node consumer.js
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      QUEUE_NAME: email_queue
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}