version: "3.8"

services:
  mail:
    build: .
    ports:
      - "3001:3001"
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      QUEUE_NAME: email_queue
      PORT: 3001
      RESEND_API_KEY: ${RESEND_API_KEY}