version: "3.8"

services:
  mail:
    build: .
    command: node src/index.js
    ports:
      - "3001:3001"
    environment:
      RABBITMQ_URL:  ${RABBITMQ_URL}
      QUEUE_NAME:    email_queue
      PORT:          3001
      BREVO_API_KEY: ${BREVO_API_KEY}
      SENDER_EMAIL:  ${SENDER_EMAIL}
